proxy:
  extends:
    file: docker-common.yml
    service: proxy
  hostname: development-${LOGNAME}
server:
  extends:
    file: docker-common.yml
    service: server
  hostname: development-${LOGNAME}
  volumes_from: 
   - proxy
logspout:
  extends:
    file: docker-common.yml
    service: logspout
  hostname: development-${LOGNAME}
