version: '3.4'
services:
  proxy:
    image: jwilder/nginx-proxy:1.0
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro
      - ./data/certs:/etc/nginx/certs:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
    ports:
      - 80:80
      - 443:443
    hostname: ${HOSTNAME}
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    restart: always
  server:
    image: nginxproxy/acme-companion:2.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/certs:/etc/nginx/certs:rw
    privileged: true
    hostname: ${HOSTNAME}
    volumes_from:
      - proxy
    restart: always

networks:
  default:
    name: internet
