proxy:
  extends:
    file: docker-common.yml
    service: proxy
  hostname: ${HOSTNAME}
  restart: always
server:
  extends:
    file: docker-common.yml
    service: server
  hostname: ${HOSTNAME}
  volumes_from: 
   - proxy
  restart: always
